### ISSUE TITLE
IL2CPP build failure if RPC has nullable in arguments

### ISSUE THREAD

**Issue by lordubbe** [FirstGearGames/FishNet#149]
Pulled out quite a bit of hair today not knowing why builds suddenly failed. Only after discovering [this ](https://github.com/FirstGearGames/FishNet/issues/135) issue (most likely related) and then digging through new code I found out that the culprit was a nullable int in the signature of a ServerRpc.

Not sure if FN is supposed to support nullables, but if not then a compiler error would be nice!

`Error: IL2CPP error for method 'System.Void FishNet.Runtime.GeneratedWriters___FN::Write___System.Nullable`1<System.Int32>(FishNet.Serializing.Writer,System.Nullable`1<System.Int32>)' in assembly 'C:\Users\lordubbe\GOLFIE\Golf Roguelite\Library\Bee\artifacts\WinPlayerBuildProgram\ManagedStripped\Assembly-CSharp.dll'
System.ArgumentException: An item with the same key has already been added. Key: GeneratedWriters___FN_Write___System_Nullable_1U3CSystem_Int32U3E_mB19D33940FF34FEB4F53A3949FC61EB644F8CC45_MetadataUsageId
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Unity.IL2CPP.CodeWriters.InMemoryGeneratedMethodCodeWriter.AddMetadataUsage(String identifier, MethodMetadataUsage usage)
   at Unity.IL2CPP.CodeWriters.CodeWriterExtensions.WriteMethodWithMetadataInitialization(IGeneratedMethodCodeWriter writer, String methodSignature, Action`2 writeMethodBody, String uniqueIdentifier, MethodReference methodRef, Boolean writingMethodBody)
   at Unity.IL2CPP.MethodWriter.WriteMethodDefinition(AssemblyWriteContext context, IGeneratedMethodCodeWriter writer, MethodReference method)
   at Unity.IL2CPP.SourceWriter.WriteType(SourceWritingContext context, IGeneratedMethodCodeWriter writer, TypeReference type, NPath filePath, Boolean writeMarshalingDefinitions)
   at Unity.IL2CPP.SourceWriters.SourceWriterBase`2.WriteItem(StreamWorkItemData`2 data)
   at Unity.IL2CPP.Contexts.Scheduling.Streams.FileLevelParallelStreamManager`3.WorkerWriteItemsToFile(WorkItemData`2 data)
   at Unity.IL2CPP.Contexts.Scheduling.PhaseWorkScheduler`1.WorkerLoop(Object data)
Error: IL2CPP error (no further information about what managed code was being converted is available)
System.InvalidOperationException: Failed to compare two elements in the array.
 ---> System.ArgumentException: Unhandled compare for
System.Void FishNet.Runtime.GeneratedWriters___FN::Write___System.Nullable`1<System.Int32>(FishNet.Serializing.Writer,System.Nullable`1<System.Int32>)
and
System.Void FishNet.Runtime.GeneratedWriters___FN::Write___System.Nullable`1<System.Int32>(FishNet.Serializing.Writer,System.Nullable`1<System.Int32>)

Assembly Qualified Names were
System.Void, mscorlib FishNet.Runtime.GeneratedWriters___FN, Assembly-CSharp::Write___System.Nullable`1<System.Int32>(FishNet.Serializing.Writer, FishNet.Runtime,System.Nullable`1, mscorlib[[System.Int32, mscorlib]])
and
System.Void, mscorlib FishNet.Runtime.GeneratedWriters___FN, Assembly-CSharp::Write___System.Nullable`1<System.Int32>(FishNet.Serializing.Writer, FishNet.Runtime,System.Nullable`1, mscorlib[[System.Int32, mscorlib]])

   at Unity.IL2CPP.DataModel.Awesome.Ordering.OrderingCompareExtensions.ThrowFailureException(String xToString, String yToString, String xAssemblyQualifiedName, String yAssemblyQualifiedName)
   at Unity.IL2CPP.DataModel.Awesome.Ordering.OrderingCompareExtensions.Compare(MethodDefinition x, MethodDefinition y)
   at Unity.IL2CPP.DataModel.Awesome.Ordering.OrderingCompareExtensions.Compare(MethodReference x, MethodReference y)
   at System.Collections.Generic.ArraySortHelper`1.InsertionSort(Span`1 keys, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(Span`1 keys, Int32 depthLimit, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(Span`1 keys, Int32 depthLimit, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(Span`1 keys, Int32 depthLimit, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(Span`1 keys, Int32 depthLimit, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(Span`1 keys, Int32 depthLimit, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(Span`1 keys, Int32 depthLimit, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(Span`1 keys, Int32 depthLimit, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(Span`1 keys, Int32 depthLimit, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(Span`1 keys, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1 keys, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1 keys, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Int32 index, Int32 count, IComparer`1 comparer)
   at Unity.IL2CPP.Contexts.Components.MethodCollectorComponent.SortItems(List`1 items)
   at Unity.IL2CPP.Contexts.Components.Base.ItemsWithMetadataIndexCollectorPhaseSortSupport`4.PhaseSortItems()
   at Unity.IL2CPP.AssemblyConversion.Steps.Base.ContextFreeScheduledStep`1.WorkerWrapper(Object unusedContext)
   at Unity.IL2CPP.Contexts.Scheduling.PhaseWorkScheduler`1.WorkerLoop(Object data)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)`

**Comment by FirstGearGames** [comment]
Likely a bug because nullables are supported.

**Comment by FirstGearGames** [comment]
related: https://github.com/FirstGearGames/FishNet/issues/135

**Comment by FirstGearGames** [comment]
I actually need more information such as the RPC, the data you're sending, the editor version, FN version.

**Comment by FirstGearGames** [comment]
Disregard. Resolved in 2.6.0
