### ISSUE TITLE
Error: IL2CPP error for method. WebGl Build

### ISSUE THREAD

**Issue by SnaiperoG3D** [FirstGearGames/FishNet#561]
Unity version: 2021.3.30f1
Fish-Networking version: 3.11.10, 3.10.5
Discord link: https://discord.com/channels/424284635074134018/1034477094731784302/1177963416460206121

**Description**
Build error for WebGl

```C:\Program Files\Unity\Hub\Editor\2021.3.30f1\Editor\Data\il2cpp\build\deploy\il2cpp.exe --convert-to-cpp --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/Assembly-CSharp.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/FishNet.Demos.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/FishNet.Runtime.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/GameKit.Dependencies.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/GameKit.Utilities.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/Mono.Security.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/mscorlib.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/System.Configuration.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/System.Core.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/System.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/System.Runtime.Serialization.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/System.Xml.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UmbraEvolution.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UmbraEvolution.PerLayerCameraCulling.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/Unity.Burst.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/Unity.Mathematics.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/Unity.RenderPipeline.Universal.ShaderLibrary.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/Unity.RenderPipelines.Core.Runtime.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/Unity.RenderPipelines.Universal.Runtime.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/Unity.TextMeshPro.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.AIModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.AndroidJNIModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.AnimationModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.AssetBundleModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.AudioModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.CoreModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.DirectorModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.GridModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.ImageConversionModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.IMGUIModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.InputLegacyModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.InputModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.JSONSerializeModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.ParticleSystemModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.Physics2DModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.PhysicsModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.SharedInternalsModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.SpriteShapeModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.SubsystemsModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.TerrainModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.TerrainPhysicsModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.TextCoreFontEngineModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.TextCoreTextEngineModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.TextRenderingModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.TilemapModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.UI.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.UIElementsModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.UIElementsNativeModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.UIModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.UNETModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.UnityAnalyticsModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.UnityWebRequestModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.UnityWebRequestTextureModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.VehiclesModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.VFXModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.VideoModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.VRModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.WindModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.XRModule.dll --data-folder=D:/BACKUP/Unity/unity_projects/YG_Unturned/YG_Unturned/Library/Bee/artifacts/WebGL/il2cppOutput/data --generatedcppdir=D:/BACKUP/Unity/unity_projects/YG_Unturned/YG_Unturned/Library/Bee/artifacts/WebGL/il2cppOutput/cpp --symbols-folder=D:/BACKUP/Unity/unity_projects/YG_Unturned/YG_Unturned/Library/Bee/artifacts/WebGL/il2cppOutput/cpp/Symbols --enable-analytics --emit-method-map --generics-option=None,EnableFullSharing --dotnetprofile=unityaot-linux --profiler-report --profiler-output-file=D:/BACKUP/Unity/unity_projects/YG_Unturned/YG_Unturned/Library/Bee/artifacts/il2cpp_conv_j7xf.traceevents --print-command-line
Error: IL2CPP error for method 'System.Void CharacterSystem::RpcLogic___CmdRequestThrowObject_3913181018(UnityEngine.Vector3,UnityEngine.Quaternion,System.String,UnityEngine.Vector3)' in D:/BACKUP/Unity/unity_projects/YG_Unturned/YG_Unturned/Assets/UnitZ/Scripts/CharacterSystem/CharacterSystem.cs:748
System.NullReferenceException: Object reference not set to an instance of an object.
   at Unity.IL2CPP.DataModel.Awesome.CFG.ControlFlowGraphBuilder.ConnectBlock(InstructionBlock block)
   at Unity.IL2CPP.DataModel.Awesome.CFG.ControlFlowGraphBuilder.ConnectBlocks()
   at Unity.IL2CPP.DataModel.Awesome.CFG.ControlFlowGraphBuilder.CreateGraph()
   at Unity.IL2CPP.MethodBodyWriter..ctor(MethodWriteContext context, IGeneratedMethodCodeWriter writer, IRuntimeMetadataAccess metadataAccess)
   at Unity.IL2CPP.MethodWriter.WriteMethodBody(MethodWriteContext context, IGeneratedMethodCodeWriter methodBodyWriter, IRuntimeMetadataAccess metadataAccess)
   at Unity.IL2CPP.CodeWriters.CodeWriterExtensions.WriteMethodWithMetadataInitialization(IGeneratedMethodCodeWriter writer, String methodSignature, Action`2 writeMethodBody, String uniqueIdentifier, MethodReference methodRef, Boolean writingMethodBody)
   at Unity.IL2CPP.MethodWriter.WriteMethodDefinition(AssemblyWriteContext context, IGeneratedMethodCodeWriter writer, MethodReference method)
   at Unity.IL2CPP.SourceWriter.WriteTypesMethods(SourceWritingContext context, IGeneratedMethodCodeWriter writer, TypeWritingInformation& writingInformation, NPath filePath, Boolean writeMarshalingDefinitions)
   at Unity.IL2CPP.SourceWriters.SourceWriterBase`2.WriteItem(StreamWorkItemData`2 data)
   at Unity.IL2CPP.Contexts.Scheduling.Streams.FileLevelParallelStreamManager`3.WorkerWriteItemsToFile(WorkItemData`2 data)
   at Unity.IL2CPP.Contexts.Scheduling.PhaseWorkScheduler`1.WorkerLoop(Object data)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
```

**Replication**
Have no idea why it appear, tested on 2 versions. There is code part where it cause, comment method body code fix the issue, i think it somehow releated to static fields which codegen cant read properly
https://pastebin.com/8sVD8a4f

**Expected behavior**
Build

**Comment by FirstGearGames** [comment]
We are still debugging this together so I'm going to close this out to clean things up here. When we find out more I'll create another bug report with more information if needed.
