### ISSUE TITLE
Post-processing code issues after upgrading Unity

### ISSUE THREAD

**Issue by Canglangzi** [FirstGearGames/FishNet#737]
# Important
If General, Description, and Replication are not completed the issue will be closed immediately.

**General**
Unity version:  Unity6 
Fish-Networking version: 4.3.8R

I encountered a problem. I upgraded to 4.3.8RPro. I deleted the original FishNet import and the following error occurred.

The previous version pro is normal. It should be normal. I checked the project and made sure I deleted all the FishNet related

Processing assembly Library/Bee/artifacts/1900b0aE.dag/Assembly-CSharp.dll, with 137 defines and 421 references
processors: FishNet.CodeGenerating.ILCore.FishNetILPP, Unity.Jobs.CodeGen.JobsILPostProcessor, zzzUnity.Burst.CodeGen.BurstILPostProcessor
running FishNet.CodeGenerating.ILCore.FishNetILPP
FishNet.CodeGenerating.ILCore.FishNetILPP: ILPostProcessor has thrown an exception: System.ArgumentException: Member 'System.Void System.ParamArrayAttribute::.ctor()' is declared in another module and needs to be imported
   at MonoFN.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider)
   at MonoFN.Cecil.MetadataBuilder.AddCustomAttributes(ICustomAttributeProvider owner)
   at MonoFN.Cecil.MetadataBuilder.AddParameter(UInt16 sequence, ParameterDefinition parameter, ParamTable table)
   at MonoFN.Cecil.MetadataBuilder.AddParameters(MethodDefinition method)
   at MonoFN.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
   at MonoFN.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
   at MonoFN.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at MonoFN.Cecil.MetadataBuilder.AddTypes()
   at MonoFN.Cecil.MetadataBuilder.BuildTypes()
   at MonoFN.Cecil.MetadataBuilder.BuildModule()
   at MonoFN.Cecil.MetadataBuilder.BuildMetadata()
   at MonoFN.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
   at MonoFN.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at MonoFN.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   at MonoFN.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at MonoFN.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at FishNet.CodeGenerating.ILCore.FishNetILPP.Process(ICompiledAssembly compiledAssembly)
   at Unity.ILPP.Runner.PostProcessingPipeline.PostProcessAssemblyAsync(PostProcessAssemblyRequest request, Action`2 progressSink)
PostProcessing failed: System.ArgumentException: Member 'System.Void System.ParamArrayAttribute::.ctor()' is declared in another module and needs to be imported
   at MonoFN.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider)
   at MonoFN.Cecil.MetadataBuilder.AddCustomAttributes(ICustomAttributeProvider owner)
   at MonoFN.Cecil.MetadataBuilder.AddParameter(UInt16 sequence, ParameterDefinition parameter, ParamTable table)
   at MonoFN.Cecil.MetadataBuilder.AddParameters(MethodDefinition method)
   at MonoFN.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
   at MonoFN.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
   at MonoFN.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at MonoFN.Cecil.MetadataBuilder.AddTypes()
   at MonoFN.Cecil.MetadataBuilder.BuildTypes()
   at MonoFN.Cecil.MetadataBuilder.BuildModule()
   at MonoFN.Cecil.MetadataBuilder.BuildMetadata()
   at MonoFN.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
   at MonoFN.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at MonoFN.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   at MonoFN.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at MonoFN.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at FishNet.CodeGenerating.ILCore.FishNetILPP.Process(ICompiledAssembly compiledAssembly)
   at Unity.ILPP.Runner.PostProcessingPipeline.PostProcessAssemblyAsync(PostProcessAssemblyRequest request, Action`2 progressSink)
   at Unity.ILPP.Runner.PostProcessingService.PostProcessAssembly(PostProcessAssemblyRequest request, IServerStreamWriter`1 responseStream, ServerCallContext context)
Unhandled Exception: System.InvalidOperationException: Post processing failed
   at Unity.ILPP.Trigger.TriggerApp.<ProcessArgumentsAsync>d__1.MoveNext() + 0xf74
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at Unity.ILPP.Trigger.TriggerApp.<ProcessArgumentsAsync>d__1.MoveNext() + 0x1149
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xb6
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x42
   at Unity.ILPP.Trigger.TriggerApp.<RunAsync>d__0.MoveNext() + 0xc7
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xb6
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x42
   at Program.<<Main>$>d__0.MoveNext() + 0x1a3
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xb6
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x42
   at Program.<Main>(String[]) + 0x20
   at Unity.ILPP.Trigger!<BaseAddress>+0x48d4fb

**Comment by FirstGearGames** [comment]
This is a Unity bug related to corrupted caching. Often clearing temp files and your Unity library will resolve this issue. The exact cause of the issue is unknown so if this does not work please let us know on our Discord so we can help you.
