### ISSUE TITLE
Code Generating Error when comes to custom serializer with a Generic Type.

### ISSUE THREAD

**Issue by VMware233** [FirstGearGames/FishNet#750]
Unity version: 2023.2.20f1
Fish-Networking version: 4.4.1R.Pro
Discord link: https://discord.com/channels/424284635074134018/1034477094731784302/1271529809532424286

**Description**
When include this script file in the project:
```C#
using System.Runtime.CompilerServices;
using FishNet.CodeGenerating;
using FishNet.Serializing;

namespace Test
{
    public interface IGameItem
    {
        
    }

    public static class GameItemSerializationUtility
    {
        [NotSerializer]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteGameItem(this Writer writer, IGameItem gameItem)
        {
            // Some code
        }

        [NotSerializer]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static TGameItem ReadGameItem<TGameItem>(this Reader reader)
            where TGameItem : IGameItem
        {
            throw new System.NotImplementedException();
        }
    }
}
```
The Error encountered:
```
Processing assembly Library/Bee/artifacts/1900b0aEDbg.dag/Assembly-CSharp.dll, with 133 defines and 313 references
processors: FishNet.CodeGenerating.ILCore.FishNetILPP, zzzUnity.Burst.CodeGen.BurstILPostProcessor
running FishNet.CodeGenerating.ILCore.FishNetILPP
FishNet.CodeGenerating.ILCore.FishNetILPP: ILPostProcessor has thrown an exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at FishNet.CodeGenerating.Helping.Extension.CustomAttributeExtensions.HasCustomAttribute[TAttribute](ICustomAttributeProvider attributeProvider)
   at FishNet.CodeGenerating.Helping.WriterProcessor.IsGlobalSerializer(TypeReference dataTypeRef)
   at FishNet.CodeGenerating.Helping.ReaderProcessor.CreateInitializeDelegate(MethodReference readMr)
   at FishNet.CodeGenerating.Helping.ReaderProcessor.CreateInitializeDelegates()
   at FishNet.CodeGenerating.ILCore.FishNetILPP.CreateSerializerInitializeDelegates(CodegenSession session)
   at FishNet.CodeGenerating.ILCore.FishNetILPP.Process(ICompiledAssembly compiledAssembly)
   at Unity.ILPP.Runner.PostProcessingPipeline.PostProcessAssemblyAsync(PostProcessAssemblyRequest request, Action`2 progressSink)
PostProcessing failed: System.NullReferenceException: Object reference not set to an instance of an object.
   at FishNet.CodeGenerating.Helping.Extension.CustomAttributeExtensions.HasCustomAttribute[TAttribute](ICustomAttributeProvider attributeProvider)
   at FishNet.CodeGenerating.Helping.WriterProcessor.IsGlobalSerializer(TypeReference dataTypeRef)
   at FishNet.CodeGenerating.Helping.ReaderProcessor.CreateInitializeDelegate(MethodReference readMr)
   at FishNet.CodeGenerating.Helping.ReaderProcessor.CreateInitializeDelegates()
   at FishNet.CodeGenerating.ILCore.FishNetILPP.CreateSerializerInitializeDelegates(CodegenSession session)
   at FishNet.CodeGenerating.ILCore.FishNetILPP.Process(ICompiledAssembly compiledAssembly)
   at Unity.ILPP.Runner.PostProcessingPipeline.PostProcessAssemblyAsync(PostProcessAssemblyRequest request, Action`2 progressSink)
   at Unity.ILPP.Runner.PostProcessingService.PostProcessAssembly(PostProcessAssemblyRequest request, IServerStreamWriter`1 responseStream, ServerCallContext context)
Unhandled Exception: System.InvalidOperationException: Post processing failed
   at Unity.ILPP.Trigger.TriggerApp.<ProcessArgumentsAsync>d__1.MoveNext() + 0xf74
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at Unity.ILPP.Trigger.TriggerApp.<ProcessArgumentsAsync>d__1.MoveNext() + 0x1149
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xb6
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x42
   at Unity.ILPP.Trigger.TriggerApp.<RunAsync>d__0.MoveNext() + 0xc7
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xb6
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x42
   at Program.<<Main>$>d__0.MoveNext() + 0x1a3
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xb6
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x42
   at Program.<Main>(String[]) + 0x20
   at Unity.ILPP.Trigger!<BaseAddress>+0x48d4fb
```

**Comment by FirstGearGames** [comment]
This is unfortunately not something supported. We support interfaces and inheritance but not generics.

**Comment by VMware233** [comment]
> This is unfortunately not something supported. We support interfaces and inheritance but not generics.
> 
> I'm going to close the issue to keep things organized but you're welcome to discuss further with me here.

I dont treat these two functions as custom reader/writer, but a utility function.And the [NotSerializer] not worked.
